# Generated by Django 4.0 on 2021-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('total_sales', models.IntegerField(max_length=100)),
                ('target_sales', models.IntegerField(max_length=100)),
                ('state', models.CharField(max_length=60)),
            ],
        ),
    ]
